### ISSUE TITLE
`oav` not throwing expected READONLY_PROPERTY_NOT_ALLOWED_IN_REQUEST

### ISSUE THREAD

**Issue by scbedd** [Azure/oav#1063]
The spec that is reproing this issue is currently still private. Contact `scbedd` for details.

**Comment by mikeharder** [comment]
I think the core of the issue is just about whether `oav` correctly enforces `readOnly` as a sibling of `$ref`.

https://github.com/Azure/autorest/blob/main/docs/openapi/howto/%24ref-siblings.md#readonly

## Specs
### Nested
```
Foo:
  myProp:
    $ref: "#Bar"
    readOnly: true
Bar:
  type: string
```

### De-Referenced
```
  Foo:
    myProp:
      type: string
      readonly: true
```

## Expected
`oav` throws error `READONLY_PROPERTY_NOT_ALLOWED_IN_REQUEST` for both specs

## Actual
`oav` throws error `READONLY_PROPERTY_NOT_ALLOWED_IN_REQUEST` for the de-referenced spec, but not the nested spec

## Code
oav has code that attempts to handle this.  But the code might have a bug, or perhaps a caller is setting `keepRefSiblings` to `false` instead of `true`?

https://github.com/Azure/oav/blob/34ac3be348de63af16b548dc7095771fb5c174cc/lib/swagger/jsonLoader.ts#L137-L141
