### ISSUE TITLE
Two examples of same shape, oav report error for only one.

### ISSUE THREAD

**Issue by anuchandy** [Azure/oav#325]
Refer: https://travis-ci.org/Azure/azure-rest-api-specs/jobs/427480126

Following two examples has the same shape.

1. https://github.com/Azure/azure-rest-api-specs/blob/76883a32f2c9aa596a7c0ceefb356637708d6ed3/specification/mysql/resource-manager/Microsoft.DBforMySQL/stable/2017-12-01/examples/ServerCreateGeoRestoreMode.json

2. https://github.com/Azure/azure-rest-api-specs/blob/76883a32f2c9aa596a7c0ceefb356637708d6ed3/specification/mysql/resource-manager/Microsoft.DBforMySQL/stable/2017-12-01/examples/ServerCreatePointInTimeRestore.json

but oav reports error for only one example, ServerCreateGeoRestoreMode.json.

```
operationId: Servers_Create
scenario: 'Create a server as a geo restore '
source: request
responseCode: ALL
severity: 0
errorCode: ONE_OF_MULTIPLE
errorDetails:
  code: ONE_OF_MULTIPLE
  params: []
  message: Data is valid against more than one schema from 'oneOf'
  path: properties
  title: /definitions/ServerForCreate/properties/properties
  description: Properties of the server.
  position:
    line: 1582
    column: 23
  url: >-
    c:\code\azure-rest-api-specs\specification\mysql\resource-manager\Microsoft.DBforMySQL\stable\2017-12-01\mysql.json

```
