### ISSUE TITLE
Model Validation error if unusual JSON content type

### ISSUE THREAD

**Issue by lmazuel** [Azure/oav#699]
ShemaRegistry has a unusual content-type `"application/json; serialization=avro"`. It's used correctly in both the operation, and the x-ms-examples. However, it makes OAV angry:

```
operationId: Schema_GetById
scenario: Get schema by ID
source: response
responseCode: '200'
severity: 1
code: INVALID_CONTENT_TYPE
details:
  code: INVALID_CONTENT_TYPE
  message: >-
    Invalid Content-Type (application/json).  These are supported:
    application/json; serialization=avro
  path: ''
  jsonPath: ''
```

We checked the Swagger several times, and we strongly believe everything is right, and this is a OAV bug.

PS: https://github.com/Azure/azure-rest-api-specs/pull/15855
