### ISSUE TITLE
semantic validation a github url will cause JSON_PARSING_ERROR

### ISSUE THREAD

**Issue by ankhyk** [Azure/oav#703]
when running `oav validate-spec (a github url for the spec path)`, it will report JSON_PARSING_ERROR

for example:
``` 
oav validate-spec https://github.com/Azure/autorest.testserver/blob/main/swagger/azure-special-properties.json
Semantically validating https://github.com/Azure/autorest.testserver/blob/main/swagger/azure-special-properties.json

Errors reported:

code: JSON_PARSING_ERROR
message: 'Json parsing error: invalid symbol'
position:
  line: 7
  column: 1
url: >-
  https://github.com/Azure/autorest.testserver/blob/main/swagger/azure-special-properties.json
```
