### ISSUE TITLE
Generated sample doesn't include name

### ISSUE THREAD

**Issue by abatishchev** [Azure/oav#788]
Swagger:

```json
{
  "Category": {
    "type": "object",
    "properties": {
      "properties": {
        "$ref": "#/definitions/CategoryProperties",
        "description": "The resource-specific properties for this resource.",
        "x-ms-mutability": [
          "read",
          "create"
        ],
        "x-ms-client-flatten": true
      },
      "systemData": {
        "$ref": "../../../../../common-types/resource-management/v3/types.json#/definitions/systemData",
        "description": "System metadata for this resource.",
        "readOnly": true
      },
      "name": {
        "type": "string",
        "description": "Category name",
        "readOnly": true
      }
    },
    "description": "Throttling category",
    "required": [
      "properties",
      "name"
    ],
    "allOf": [
      {
        "$ref": "../../../../../common-types/resource-management/v3/types.json#/definitions/ProxyResource"
      }
    ]
  },
```

Sample (Categories_CreateOrUpdate_MaximumSet_Gen.json):

```json
{
  "parameters": {
    "api-version": "2022-06-01-preview",
    "subscriptionId": "aaaaaaaaaaaaaaaaaaaa",
    "resourceGroupName": "rgthrottling",
    "accountName": "aaaaa",
    "categoryName": "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
    "resource": {
      "properties": {
        "windowDuration": "aaaaaaaaaaaa"
      }
    }
  }
  "responses": {
    "200": {
      "body": {
        "properties": {
          "windowDuration": "aaaaaaaaaaaa"
        },
        "systemData": {
          "createdBy": "a",
          "createdByType": "User",
          "createdAt": "2022-05-04T20:28:44.075Z",
          "lastModifiedBy": "a",
          "lastModifiedByType": "User",
          "lastModifiedAt": "2022-05-04T20:28:44.075Z"
        },
        "name": "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
        "id": "aaaaaaaaaaaaaaaaaaaa",
        "type": "aaaaaaaaaaaaaaa"
      }
    }
}
```

The response does include name, but the request does not, hence an error during Shift Left validation:

```
code: OBJECT_MISSING_REQUIRED_PROPERTY
message: 'Missing required property: name'
schemaUrl: >-
  specification/throttling/resource-manager/Microsoft.Throttling/preview/2022-06-01-preview/throttling.json
exampleUrl: >-
  specification/throttling/resource-manager/Microsoft.Throttling/preview/2022-06-01-preview/examples/Categories_CreateOrUpdate_MaximumSet_Gen.json
schemaPosition:
  line: 1138
  column: 17
schemaJsonPath: '#/required'
examplePosition:
  line: 8
  column: 17
exampleJsonPath: $parameters.resource
severity: 0
source: request
operationId: Categories_CreateOrUpdate
level: error
```
